management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
spring:
  data:
   mongodb:
     authentication-database: admin
#     host:
#     uri: mongodb://root:example@localhost:27017/urlshortener
     host: localhost
     database: urlshortener
     port: 27017
     username: root
     password: example
